In [1]:
import h5py
import pandas as pd

In [2]:
hf = h5py.File('../data/book_events_total_view_2017-01-03.h5', 'r')
# List all groups
print("Keys: %s" % hf.keys())
a_group_key = list(hf.keys())[0]
data = list(hf[a_group_key])
hf.close()

Keys: KeysView(<HDF5 file "book_events_total_view_2017-01-03.h5" (mode r)>)

In [3]:
df = pd.read_hdf('../data/book_events_total_view_2017-01-03.h5', key = a_group_key)

In [19]:
df

,timestamp,order_id,book_event_type,price,quantity,aux_quantity,side,aux1,aux2
0,1483444800275600142,4470789,A,199999990000000,100,0,A,0,0
1,1483444800275600142,4470793,A,10000000,100,0,B,0,0
2,1483444800285514131,4471001,A,46980000000,400,0,A,0,0
3,1483444800289616465,4471117,A,34150000000,10,0,B,0,0
4,1483448400670346058,6150861,A,32740000000,50,0,B,0,0
5,1483448400670612581,6150865,A,34860000000,5,0,B,0,0
6,1483448414452171899,6197537,A,34860000000,50,0,B,0,0
7,1483448417876939699,6207601,A,42120000000,180,0,B,0,0
8,1483448421837995760,6213085,A,46970000000,180,0,A,0,0
9,1483450111733579501,6207601,C,42120000000,0,180,B,0,0
10,1483450116887144394,6213085,C,46970000000,0,180,A,0,0
11,1483450346447432599,7643677,A,42120000000,180,0,B,0,0
12,1483450354969540804,7648633,A,46970000000,180,0,A,0,0
13,1483452001061317794,8691681,A,33700000000,100,0,B,0,0
14,1483452001063932910,8691697,A,56360000000,100,0,A,0,0
15,1483452660000709488,9322805,A,33700000000,100,0,B,0,0
16,1483452660325728103,9327629,A,56360000000,100,0,A,0,0
17,1483453050555455207,9663065,A,40220000000,100,0,B,0,0
18,1483453050555480517,9663069,A,49080000000,100,0,A,0,0
19,1483453058013998322,9663065,C,40220000000,0,100,B,0,0
20,1483453058014010772,9663069,C,49080000000,0,100,A,0,0
21,1483453200047311186,9824269,A,46960000000,100,0,A,0,0
22,1483453200047311186,9824273,A,42130000000,100,0,B,0,0
23,1483453204201380111,9839485,A,44190000000,26,0,B,0,0
24,1483453204201416052,9824273,C,42130000000,0,100,B,0,0
25,1483453204201416052,9824269,C,46960000000,0,100,A,0,0
26,1483453205049355581,9847769,A,42570000000,100,0,B,0,0
27,1483453210048061750,9847769,C,42570000000,0,100,B,0,0
28,1483453227234804794,7643677,C,42120000000,0,180,B,0,0
29,1483453227235193312,9921981,A,42790000000,180,0,B,0,0
...,...,...,...,...,...,...,...,...,...
132009,1483481279893280647,281616257,C,46830000000,0,300,A,0,0
132010,1483481281143618322,281631349,A,46830000000,300,0,A,0,0
132011,1483481339923320583,281631349,C,46830000000,0,300,A,0,0
132012,1483481341173608370,281646297,A,46830000000,300,0,A,0,0
132013,1483481399953450441,281646297,C,46830000000,0,300,A,0,0
132014,1483481401203580521,281661633,A,46830000000,300,0,A,0,0
132015,1483481406773533858,281613477,C,46840000000,0,170,A,0,0
132016,1483481406774075821,281668197,A,46820000000,170,0,A,0,0
132017,1483481406775802731,281661633,C,46830000000,0,300,A,0,0
132018,1483481407453354366,281668265,A,46810000000,300,0,A,0,0
132019,1483481459983048573,281668265,C,46810000000,0,300,A,0,0
132020,1483481461233236290,281677401,A,46810000000,300,0,A,0,0
132021,1483481519773028075,281677401,C,46810000000,0,300,A,0,0
132022,1483481521023214004,281690849,A,46810000000,300,0,A,0,0
132023,1483481579802912749,281690849,C,46810000000,0,300,A,0,0
132024,1483481581053089126,281707593,A,46810000000,300,0,A,0,0
132025,1483481601946358762,281668197,C,46820000000,0,170,A,0,0
132026,1483481601946865230,281717105,A,46800000000,170,0,A,0,0
132027,1483481601948760062,281707593,C,46810000000,0,300,A,0,0
132028,1483481602553188458,281717189,A,46790000000,300,0,A,0,0
132029,1483481639832862317,281717189,C,46790000000,0,300,A,0,0
132030,1483481641083204381,281722849,A,46790000000,300,0,A,0,0
132031,1483481699842833027,281722849,C,46790000000,0,300,A,0,0
132032,1483491600048280358,281717105,C,46800000000,0,170,A,0,0
132033,1483491600049389623,4471117,C,34150000000,0,10,B,0,0
132034,1483491600059524424,248504609,C,34860000000,0,5,B,0,0
132035,1483491600065852589,248504649,C,32740000000,0,50,B,0,0
132036,1483491600072177290,248504617,C,34860000000,0,50,B,0,0
132037,1483491600072557337,280554353,C,46900000000,0,400,A,0,0
132038,1483491600074975684,281514045,C,42120000000,0,170,B,0,0

In [ ]:
# Start of Exploration

import pandas as pd
import os


df.head()
def summarize_df(dataframe):
    print("\n\n======= Book Event Type =======\n"+str(df['book_event_type'].value_counts()),"\n"+
        "======= Side =======\n"+str(df['side'].value_counts()), "\n"+
        "======= Order ID =======\n"+str(df['order_id'].value_counts()), "\n"+
        "======= Price =======\n"+str(df['price'].value_counts()),)



summarize_df(df)


sum(df.side =='U'and df.order_id == 0) # trade type T is the same as side U and order_id 0

mod_df = (df[df.book_event_type == 'M'])
trade_df = (df[df.book_event_type == 'T'])

In [ ]:
h5f = h5py.File('features.h5', 'w')
h5f.create_dataset('training_data', data=training_data)
h5f.close()

In [ ]:
# Start of Project Pre-Processing using CSV

import pandas as pd
import os

os.chdir('C:\\Users\\alxgr\\Documents\\UVA\\DSI\\Spring 2019\\ML\\Project')
df = pd.read_csv("./Data_Project-1-Prediction_Book_event_levelII_BAC_book_events_sip-nyse_2016-05-02.csv")
df.head()

def summarize_df(dataframe):
    print("\n\n======= Book Event Type =======\n"+str(df['book_event_type'].value_counts()),"\n"+
        "======= Side =======\n"+str(df['side'].value_counts()), "\n"+
        "======= Order ID =======\n"+str(df['order_id'].value_counts()), "\n"+
        "======= Price =======\n"+str(df['price'].value_counts()),)



summarize_df(df)


sum(df.side =='U'and df.order_id == 0)